name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Docker Build & Push
        uses: mr-smithers-excellent/docker-build-push@v4.0
        with:
          image: andrijdavid/noisy
          registry: docker.io 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

